### ISSUE TITLE
segmentation fault on single-node run for scale24-25

### ISSUE THREAD

**Issue by yvdriess** [graph500/graph500#10]
A single-node at Toy scale (scale 25, edge factor 16) causes a segmentation fault in the AML library during graph generation. The trace below originates from bfs_custom.c, but bfs_reference.c causes the exact same error.

To reproduce: make && ./graph500_reference_bfs 25 16

System: ubuntu LTS 16.04
Toolchain: gcc-5.4.0, libc 2.23-0ubuntu9

```
53        return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
(gdb) bt
#0  0x0000000000403632 in memcpy (__len=6, __src=0x7fffffffd930, __dest=0x7ffe08ea4842)
    at /usr/include/x86_64-linux-gnu/bits/string3.h:53
#1  fulledgehndl (frompe=<optimized out>, data=<optimized out>, sz=<optimized out>) at csr_reference.c:43
#2  0x0000000000405d43 in aml_send (src=src@entry=0x7fffffffda60, type=type@entry=1, length=length@entry=12,
    node=<optimized out>) at ../aml/aml.c:287
#3  0x0000000000403e5e in send_full_edge (tgt=10478974, src=16314982) at csr_reference.c:71
#4  convert_graph_to_oned_csr (tg=tg@entry=0x7fffffffdb90, g=g@entry=0x6b6c00 <g>) at csr_reference.c:173
#5  0x0000000000403046 in make_graph_data_structure (tg=tg@entry=0x7fffffffdb90) at bfs_custom.c:39
#6  0x0000000000401d4a in main (argc=3, argv=0x7fffffffdd48) at main.c:297

(gdb) f 5
#5  0x0000000000403046 in make_graph_data_structure (tg=tg@entry=0x7fffffffdb90) at bfs_custom.c:39
39        convert_graph_to_oned_csr(tg, &g);
```

**Comment by akorzh** [comment]
I will look into that once get back from Supercomputing, 
So far that works fine on my Mac. and does running it through mpirun -n 2 also fails? cause this is mph binary and is not suggested to run without mpirun. and BTW which MPI have you used - I will need to reproduce it

**Comment by usr-sse2** [comment]
on my Mac it crashes with mpirun -n 1 (mpich from Homebrew, gcc 7.2.0) at graph scale 2 or 3, edgefactor 1 (but it is an externally generated graph). For bigger graphs it works and produces correct result. I'll attach the graph soon.

**Comment by usr-sse2** [comment]
Here are the graphs and logs (run like this: `VERBOSE=1 SKIP_BFS=1 TMPFILE=RMAT_"$S"_"$EF" REUSEFILE=1 mpirun -np 1 ./graph500_reference_bfs_sssp $S $EF`, where S and EF are assigned to scale and edge factor). 
[RMAT_2_1.zip](https://github.com/graph500/graph500/files/1480208/RMAT_2_1.zip)
[RMAT_3_1.zip](https://github.com/graph500/graph500/files/1480209/RMAT_3_1.zip)
[RMAT_4_1.zip](https://github.com/graph500/graph500/files/1480210/RMAT_4_1.zip)

**Comment by akorzh** [comment]
some update on the issue: find the cause and it seems to be wrong type used indeed so 24 might be fixed by changing few signed int types to unsigned but otherwise it looks to be a fundamental limitation of the code to have a scale 25 being max per one process as we use 32-bit to index local edges. Of course changing that type to 64-bit would fix everything but it would degrade performance and increase memory consumption and still scale 32 is max per process as local vertex id is 32-bit and that is not going to change. I consider changing type to 64-bit in reference code though. might take a while, cause i am working on optimized code and that has priority for now

**Comment by mark-i-m** [comment]
I'm running into this as well. I would like to use graph500 on a single huge-memory node (1TB DRAM), but I keep getting a segfault at anything larger than a toy problem. Is there a possibility of have an ifdef to define the type of the indices?

**Comment by Qinghe12** [comment]
@akorzh  Hi, I met same problem. Have you finished changing type to 64-bit to index local edges in reference code? actually, I do not care performance drop and memory consumption...

**Comment by matte21** [comment]
I'm running into this. Is there any solution?
